version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynet

  web:
    build: ./web
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
    ports:
      - "80:8000"
    depends_on:
      - db
    networks:
      - mynet
    deploy:
      replicas: 2

volumes:
  db_data:

networks:
  mynet:
    driver: bridge
